project:
  type: website

website:
  title: "closeRead_saint_jacut"
  navbar:
    left:
      - href: index.qmd
        text: Saint-JActude la mer
      - href: test.qmd
        text: Tests

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
