project:
  type: website

website:
  title: "CloseRead"
  navbar:
    left:
      - href: index.qmd
        text: Saint-Jacut-de-la-Mer
      - href: index_en.qmd
        text: En anglais
      - href: formation.qmd
        text: Formation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
