project:
  type: website

website:
  title: "closeRead_saint_jacut"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
